[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_dapp = "65D1me4RDs45aHUb59Uv7RcGFivkxvFVTDoDWvNfaE41"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thanhvk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
